# Yarn configuration file
# See https://yarnpkg.com/configuration/yarnrc for more details on available options and their meanings.
# This configuration sets the node linker to use the traditional node_modules structure,
# specifies the npm registry, and defines a custom Yarn binary path.

registry: "https://registry.yarnpkg.com"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.11.0.cjs
