version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: fintrack-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: fintrack
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fintrack-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fintrack --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # FinTrack API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fintrack-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/fintrack
      - JWT_SECRET=${JWT_SECRET:-fintrack-secret-key-change-in-production}
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=*
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - fintrack-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data:
    driver: local

networks:
  fintrack-network:
    driver: bridge
