# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Workflow to publish Docker image to GitHub Container Registry (GHCR)
# Triggered on push to main branch or when a new release is created
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

name: 'Publish: Docker Image to GHCR'
run-name: 'Publish to GHCR by @${{ github.actor }} on ${{ github.event_name }}'

on:
  workflow_dispatch: # ✅ Cho phép chạy thủ công
  repository_dispatch: # ✅ Cho phép kích hoạt từ bên ngoài (ví dụ: từ một workflow khác)
  # push:
  #   branches: ['main']
  #   tags:
  #     - 'v*'
  release:
    # created : # ✅ Chỉ chạy khi release được tạo
    # published: # ✅ Chỉ chạy khi release được phát hành
    types: [created] # ✅ Chỉ chạy khi release được tạo

# Remove all permissions by default
permissions: write-all

env:
  SERVER: production
  BRANCH: ${{ github.ref_name }}
  REPO_NAME: # ✅ Sẽ được gán động trong steps
  REPOSITORY: ${{ github.repository }}
  # ✅ Default nếu không đọc từ file VERSION
  # VERSION: ${{ ((github.ref_type == 'branch' && github.ref_name == 'main') || (github.ref_type == 'tag')) && format('1.0.{0}', github.run_number) || format('1.0.{0}-dev', github.run_number) }}
  VERSION: >-
    ${{
      github.ref_type == 'branch' && github.ref_name == 'main'
        && format('1.0.{0}-main', github.run_number)
        || github.ref_type == 'tag'
        && format('1.0.{0}', github.run_number)
        || format('1.0.{0}-dev', github.run_number)
    }}

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Make sure to fetch full history for changelog generation

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Sử dụng Node.js 22
